### ISSUE TITLE
fit=mst.mle(design, response, start=para, fixed.df=NA, trace=FALSE, algorithm="BFGS", control = list(fnscale=-1) )      

### ISSUE THREAD

**Issue by reem-hassan** [waldronlab/doppelgangR#20]
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
>

**Comment by lwaldron** [comment]
Hi @reem-hassan, can you provide some context here, and better a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? I'm sorry I don't yet have any idea what the problem might be.
