### ISSUE TITLE
Try to speed up by sampling genes.

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/doppelgangR#8]
Try using only a sample of say 200 genes - if it speeds up the correlation computations and gives nearly identical results, may be worth adding a discussion to the Vignette.  Not necessary to offer as an option to the package.

**Comment by lima1** [comment]
I would use lapply(testesets, varFilter, var.cutoff=0.9)

**Comment by lwaldron** [comment]
Good idea, better than sampling.

**Comment by lima1** [comment]
var.cutoff is probably slightly too high. you used 200 genes present on both platforms in each pair?
